# The config file for the plugin is fairly simple, each section has it's explanation above
# Made by 3add

AddsCommandHider:

  # All the commands the server will block, each command can have it's own bypass permission
  # (If you wish for the command to be blocked for all players, leave it empty)
  BlockedCommands:
    - plugins: "CommandHider.bypass"

  # If the plugin should deny the namespace usage (/namespace:command)
  BlockedNamespaces: true